version: "3.8"
services:
  postgresql:
    container_name: ecommerce-pg
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  # redis:
  #   container_name: redis
  #   image: redis:latest
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - "6379:6379"
  #   environment:
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #   command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  pgdata: # Khai báo volume ở đây
